include:
   - infra.yaml
services:
   rasa:
    image: rasa/rasa:3.6.20
    build:
      context: .
    volumes:
      - ./data:/app/data
    ports:
      - "5005:5005"
    command:
      python -m rasa run  --enable-api  --endpoints endpoints.yml --credentials credentials.yml --debug
    networks:
      - rasa-networks
networks:
  rasa-networks: