services:
  action:
    image: action_server
    build:
      context: ./actions
    volumes:
      - ./actions:/app
    ports:
      - "5055:5055"
    command : python -m rasa run  actions
    networks:
      - rasa-networks